version: '3.8'
services:
  node:
    build: .
    pull_policy: build
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - RCON_PASSWORD=${RCON_PASSWORD}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - STOP_TIMEOUT=${STOP_TIMEOUT}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DISCORD_MESSAGE_ID=${DISCORD_MESSAGE_ID}
    container_name: portainer-discord-manager