version: '3.8'
services:
  node:
    build: .
    pull_policy: build
    restart: unless-stopped
    volumes:
      - ./src/data:/usr/src/app/src/data
    environment:
      - NODE_ENV=production
      - RCON_PASSWORD=
      - SERVER_ADDRESS=
      - STOP_TIMEOUT=15
      - DISCORD_TOKEN=
      - DISCORD_CHANNEL_ID=
    container_name: portainer-discord-manager